### ISSUE TITLE
No linebreak in Cell.setText() possible

### ISSUE THREAD

**Issue by derehls** [dhorions/boxable#31]
`Cell.setText("Hello\nWorld")`

Leads to 

U+000A ('controlLF') is not available in this font's encoding: WinAnsiEncoding

`java.lang.IllegalArgumentException: U+000A ('controlLF') is not available in this font's encoding: WinAnsiEncoding
	at org.apache.pdfbox.pdmodel.font.PDType1Font.encode(PDType1Font.java:344)
	at org.apache.pdfbox.pdmodel.font.PDFont.encode(PDFont.java:285)
	at org.apache.pdfbox.pdmodel.font.PDFont.getStringWidth(PDFont.java:314)
	at be.quodlibet.boxable.Paragraph.getLines(Paragraph.java:83)
	at be.quodlibet.boxable.Paragraph.getHeight(Paragraph.java:154)
	at be.quodlibet.boxable.Cell.getTextHeight(Cell.java:391)
	at be.quodlibet.boxable.Cell.getCellHeight(Cell.java:366)
	at be.quodlibet.boxable.Row.getHeight(Row.java:159)
	at be.quodlibet.boxable.Table.getMinimumHeight(Table.java:703)
	at be.quodlibet.boxable.Table.draw(Table.java:192)`

**Comment by Frulenzo** [comment]
If you want some kind of text formatting you will need to adjust correct wrapping function in `Paragraph` class. Check a little bit this #9 and specially last post by @dobluth

**Comment by derehls** [comment]
As I understand and tested the WrappingFunction only controls what are possible points to wrap the text when it exceeds the width of the Cell. But what I want is forcing a linebreak, regardless if there is still space left in the Cell. I think this hast to be implemented in Paragraph.java.

**Comment by Frulenzo** [comment]
Yeah, that is why there are called possibleWrapPoints. Ofcourse you can make list called wrapPoints where you mark your "must have" wrapping point occurrences and then you just say:
```java
if(wrapPoints.contains(i)) {
    result.add(text.substring(start, end));
    start = end; 
}
```

Hopefully that answer your question :)

**Comment by Frulenzo** [comment]
If you to enforce linebreaks in form of HTML tag (<br>, <br />), that would be accessible after merging #34

**Comment by dhorions** [comment]
This should now be possible after merging #34
