### ISSUE TITLE
Special Characters in Cell causes IllegalArgumentException 

### ISSUE THREAD

**Issue by gstrickland** [dhorions/boxable#96]
I have some data in a Cell that contains (I think) a tab character. When I call Table.getHeaderAndDataHeight the following Exception is thrown. 
I only reproduced part of the stack trace, because I am unfortunately developing on a machine that has no ability to connect to the internet, so I can't copy and paste the stack trace. I had to transcribe this stacktrace manually.
Should I cleanse the data that goes into the cell to eliminate any characters that are not available in my desired font? Is there a method in either boxable or pdfbox that can tell me if a String contains such characters?
Is this an issue in pdfbox? I encountered it in a boxable call, so I wanted to ask you. 

Caused by: java.lang.IllegalArgumentException: U+0009 ('controlHT') is not available in this font Helvetica (generic: LiberationSans) encoding: WinAnsiEncoding
        at org.apache.pdfobx.pdmodel.font.PDType1Font.encode(PDType1Font.java:406) [pdfbox-2.0.2.jar:2.0.4]
		at org.apache.pdfbox.pdmodel.font.PDFont.encode(PDFont.java:316) [pdfbox-2.0.2.jar:2.0.4]
		at org.apache.pdfbox.pdmodel.font.PDFont.getStringWidth(PDFont.java:345) [pdfbox-2.0.2.jar:2.0.4]
		at be.quodlibet.boxable.Paragraph.getLines(Paragraph.java:352) [boxable-1.5-RC.jar:]
		at be.quodlibet.boxable.Paragraph.getHeight(Paragraph.java:541) [boxable-1.5-RC.jar:]
		at be.quodlibet.boxable.Cell.getTextHeight(Cell.java:392) [boxable-1.5-RC.jar:]
		at be.quodlibet.boxable.Cell.getCellHeight(Cell.java:367) [boxable-1.5-RC.jar:]
		at be.quodlibet.boxable.Row.getHeight(Row.java:161) [boxable-1.5-RC.jar:]
		at be.quodlibet.boxable.Table.getHeaderAndDataHeight(Table.java:799) [boxable-1.5-RC.jar:]
		at my.code.AttachmentBuilder.drawTable(AttachmentBuilder.java:512) [my.jar:]

**Comment by Frulenzo** [comment]
I already mention that we have some issue due special charachters encoding. Your problem can be temporary solved with something like this

```java
cellText = cellText.replace("\u+0009", "    ");
```
All special charachters should be avoided in this manner. Better solution would be using other default font that supports WinAnsiEncoding. More info here: #73
