### ISSUE TITLE
DataTable.addListToTable causes Exception if an element starts with "

### ISSUE THREAD

**Issue by maner** [dhorions/boxable#99]
Version 1.5RC (same error with 1.4)
(....)
  for (int i = 1; i <= 100; i++) {
            data.add(new ArrayList<>(
                    Arrays.asList("\"Row " + i + " \"Col One", "Row " + i + " Col Two", "Row " + i + " Col Three", "Row " + i + " Col Four", "Row " + i + " Col Five")));
       }
(...)

Exception in thread "main" java.lang.RuntimeException: java.io.IOException: (line 2) invalid char between encapsulated token and delimiter
	at org.apache.commons.csv.CSVParser$1.getNextRecord(CSVParser.java:442)
	at org.apache.commons.csv.CSVParser$1.hasNext(CSVParser.java:452)
	at be.quodlibet.boxable.datatable.DataTable.addCsvToTable(DataTable.java:228)
	at be.quodlibet.boxable.datatable.DataTable.addListToTable(DataTable.java:203)
Caused by: java.io.IOException: (line 2) invalid char between encapsulated token and delimiter
	at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:275)
	at org.apache.commons.csv.Lexer.nextToken(Lexer.java:152)
	at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:498)

regards
Massimo

**Comment by Frulenzo** [comment]
Hopefully it helps: http://stackoverflow.com/questions/26729799/invalid-char-between-encapsulated-token-and-delimiter-in-apache-commons-csv-libr
